name: workflow2
on:
  schedule:
    - cron: "*/2 * * * *" 
jobs:
    job2:
      runs-on : ubuntu-latest
      steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Welcome to Avd data ops class"
 